import type {
  User,
  TechEvent,
  Registration,
  Task,
  Notification,
  ActivityLog,
} from "./types"

export const USERS: User[] = [
  {
    id: "u1",
    name: "Arjun Mehta",
    email: "arjun@techfest.io",
    role: "super_admin",
    avatar: "",
    createdAt: "2025-12-01T10:00:00Z",
  },
  {
    id: "u2",
    name: "Priya Sharma",
    email: "priya@techfest.io",
    role: "admin",
    avatar: "",
    createdAt: "2025-12-05T10:00:00Z",
  },
  {
    id: "u3",
    name: "Dr. Rajesh Kumar",
    email: "rajesh@techfest.io",
    role: "faculty_coordinator",
    avatar: "",
    createdAt: "2025-12-10T10:00:00Z",
  },
  {
    id: "u4",
    name: "Sneha Patel",
    email: "sneha@techfest.io",
    role: "club_coordinator",
    avatar: "",
    createdAt: "2025-12-12T10:00:00Z",
  },
  {
    id: "u5",
    name: "Vikram Singh",
    email: "vikram@techfest.io",
    role: "team_lead",
    avatar: "",
    createdAt: "2025-12-15T10:00:00Z",
  },
  {
    id: "u6",
    name: "Ananya Desai",
    email: "ananya@techfest.io",
    role: "volunteer",
    avatar: "",
    createdAt: "2025-12-18T10:00:00Z",
  },
  {
    id: "u7",
    name: "Rohan Gupta",
    email: "rohan@techfest.io",
    role: "campus_ambassador",
    avatar: "",
    referralCode: "ROHAN2026",
    createdAt: "2025-12-20T10:00:00Z",
  },
]

export const EVENTS: TechEvent[] = [
  {
    id: "e1",
    title: "AI & Machine Learning Workshop",
    description:
      "Hands-on workshop covering deep learning fundamentals with TensorFlow and PyTorch.",
    date: "2026-03-15",
    time: "10:00 AM",
    venue: "Auditorium A",
    category: "Workshop",
    status: "upcoming",
    maxRegistrations: 150,
    currentRegistrations: 89,
    coordinatorId: "u3",
    createdBy: "u2",
    createdAt: "2026-01-10T10:00:00Z",
  },
  {
    id: "e2",
    title: "Hackathon: Code Nexus",
    description:
      "36-hour hackathon with industry mentors. Build solutions for real-world problems.",
    date: "2026-03-20",
    time: "9:00 AM",
    venue: "Innovation Hub",
    category: "Competition",
    status: "upcoming",
    maxRegistrations: 200,
    currentRegistrations: 156,
    coordinatorId: "u4",
    createdBy: "u2",
    createdAt: "2026-01-12T10:00:00Z",
  },
  {
    id: "e3",
    title: "Robotics Championship",
    description:
      "Build and program autonomous robots to compete in obstacle courses.",
    date: "2026-03-22",
    time: "11:00 AM",
    venue: "Tech Arena",
    category: "Competition",
    status: "upcoming",
    maxRegistrations: 80,
    currentRegistrations: 72,
    coordinatorId: "u3",
    createdBy: "u1",
    createdAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "e4",
    title: "Cybersecurity CTF",
    description:
      "Capture The Flag competition testing hacking and defense skills.",
    date: "2026-03-25",
    time: "2:00 PM",
    venue: "Lab 201",
    category: "Competition",
    status: "upcoming",
    maxRegistrations: 100,
    currentRegistrations: 45,
    coordinatorId: "u4",
    createdBy: "u2",
    createdAt: "2026-01-18T10:00:00Z",
  },
  {
    id: "e5",
    title: "Tech Talk: Future of Web3",
    description:
      "Industry experts discuss blockchain, decentralization, and the future of the internet.",
    date: "2026-03-18",
    time: "3:00 PM",
    venue: "Seminar Hall",
    category: "Talk",
    status: "upcoming",
    maxRegistrations: 300,
    currentRegistrations: 210,
    coordinatorId: "u3",
    createdBy: "u1",
    createdAt: "2026-01-20T10:00:00Z",
  },
  {
    id: "e6",
    title: "UI/UX Design Sprint",
    description:
      "48-hour design sprint to create innovative user experiences.",
    date: "2026-02-28",
    time: "10:00 AM",
    venue: "Design Studio",
    category: "Workshop",
    status: "completed",
    maxRegistrations: 60,
    currentRegistrations: 60,
    coordinatorId: "u4",
    createdBy: "u2",
    createdAt: "2026-01-05T10:00:00Z",
  },
]

export const REGISTRATIONS: Registration[] = [
  {
    id: "r1",
    eventId: "e1",
    eventTitle: "AI & Machine Learning Workshop",
    userId: "u6",
    userName: "Ananya Desai",
    userEmail: "ananya@techfest.io",
    status: "approved",
    registeredAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "r2",
    eventId: "e2",
    eventTitle: "Hackathon: Code Nexus",
    userId: "u6",
    userName: "Ananya Desai",
    userEmail: "ananya@techfest.io",
    teamName: "ByteForce",
    teamMembers: ["Ananya Desai", "Karan Joshi", "Meera Nair"],
    status: "approved",
    registeredAt: "2026-02-03T10:00:00Z",
    referralCode: "ROHAN2026",
  },
  {
    id: "r3",
    eventId: "e3",
    eventTitle: "Robotics Championship",
    userId: "u7",
    userName: "Rohan Gupta",
    userEmail: "rohan@techfest.io",
    teamName: "RoboVerse",
    teamMembers: ["Rohan Gupta", "Aditya Rao"],
    status: "pending",
    registeredAt: "2026-02-10T10:00:00Z",
  },
  {
    id: "r4",
    eventId: "e4",
    eventTitle: "Cybersecurity CTF",
    userId: "u5",
    userName: "Vikram Singh",
    userEmail: "vikram@techfest.io",
    status: "pending",
    registeredAt: "2026-02-12T10:00:00Z",
  },
  {
    id: "r5",
    eventId: "e5",
    eventTitle: "Tech Talk: Future of Web3",
    userId: "u6",
    userName: "Ananya Desai",
    userEmail: "ananya@techfest.io",
    status: "approved",
    registeredAt: "2026-02-15T10:00:00Z",
  },
  {
    id: "r6",
    eventId: "e1",
    eventTitle: "AI & Machine Learning Workshop",
    userId: "u7",
    userName: "Rohan Gupta",
    userEmail: "rohan@techfest.io",
    status: "rejected",
    registeredAt: "2026-02-08T10:00:00Z",
  },
]

export const TASKS: Task[] = [
  {
    id: "t1",
    title: "Set up registration desk",
    description: "Arrange tables, chairs, and laptops for check-in at Auditorium A.",
    eventId: "e1",
    eventTitle: "AI & Machine Learning Workshop",
    assignedTo: "u6",
    assignedToName: "Ananya Desai",
    status: "todo",
    deadline: "2026-03-14",
    createdAt: "2026-02-20T10:00:00Z",
  },
  {
    id: "t2",
    title: "Coordinate with sponsors",
    description: "Contact all 5 sponsors for banners and swag delivery.",
    eventId: "e2",
    eventTitle: "Hackathon: Code Nexus",
    assignedTo: "u5",
    assignedToName: "Vikram Singh",
    status: "in_progress",
    deadline: "2026-03-18",
    createdAt: "2026-02-22T10:00:00Z",
  },
  {
    id: "t3",
    title: "Prepare arena layout",
    description: "Design and set up the obstacle course for the robotics competition.",
    eventId: "e3",
    eventTitle: "Robotics Championship",
    assignedTo: "u5",
    assignedToName: "Vikram Singh",
    status: "todo",
    deadline: "2026-03-20",
    createdAt: "2026-02-25T10:00:00Z",
  },
  {
    id: "t4",
    title: "Test CTF challenges",
    description: "Verify all 20 CTF challenges are working correctly.",
    eventId: "e4",
    eventTitle: "Cybersecurity CTF",
    assignedTo: "u6",
    assignedToName: "Ananya Desai",
    status: "completed",
    deadline: "2026-03-23",
    createdAt: "2026-02-28T10:00:00Z",
  },
  {
    id: "t5",
    title: "Social media promotion",
    description: "Create and schedule posts for all events across platforms.",
    eventId: "e2",
    eventTitle: "Hackathon: Code Nexus",
    assignedTo: "u7",
    assignedToName: "Rohan Gupta",
    status: "in_progress",
    deadline: "2026-03-10",
    createdAt: "2026-02-15T10:00:00Z",
  },
  {
    id: "t6",
    title: "Arrange guest speaker logistics",
    description: "Book travel and accommodation for 3 guest speakers.",
    eventId: "e5",
    eventTitle: "Tech Talk: Future of Web3",
    assignedTo: "u5",
    assignedToName: "Vikram Singh",
    status: "completed",
    deadline: "2026-03-15",
    createdAt: "2026-02-10T10:00:00Z",
  },
]

export const NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    title: "New Registration",
    message: "Rohan Gupta registered for Robotics Championship.",
    type: "info",
    read: false,
    createdAt: "2026-02-28T14:30:00Z",
  },
  {
    id: "n2",
    title: "Task Completed",
    message: "Ananya Desai completed 'Test CTF challenges'.",
    type: "success",
    read: false,
    createdAt: "2026-02-28T12:00:00Z",
  },
  {
    id: "n3",
    title: "Registration Limit Warning",
    message: "Robotics Championship is at 90% capacity.",
    type: "warning",
    read: true,
    createdAt: "2026-02-27T16:00:00Z",
  },
  {
    id: "n4",
    title: "Event Update",
    message: "Hackathon venue changed to Innovation Hub.",
    type: "info",
    read: true,
    createdAt: "2026-02-26T10:00:00Z",
  },
]

export const ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: "a1",
    userId: "u2",
    userName: "Priya Sharma",
    action: "Created Event",
    details: "Created 'Cybersecurity CTF'",
    timestamp: "2026-02-28T15:00:00Z",
  },
  {
    id: "a2",
    userId: "u4",
    userName: "Sneha Patel",
    action: "Approved Registration",
    details: "Approved Ananya Desai for Code Nexus",
    timestamp: "2026-02-28T14:00:00Z",
  },
  {
    id: "a3",
    userId: "u6",
    userName: "Ananya Desai",
    action: "Completed Task",
    details: "Completed 'Test CTF challenges'",
    timestamp: "2026-02-28T12:00:00Z",
  },
  {
    id: "a4",
    userId: "u1",
    userName: "Arjun Mehta",
    action: "Created Admin",
    details: "Added Priya Sharma as Admin",
    timestamp: "2026-02-27T10:00:00Z",
  },
  {
    id: "a5",
    userId: "u5",
    userName: "Vikram Singh",
    action: "Updated Task",
    details: "Moved 'Coordinate with sponsors' to In Progress",
    timestamp: "2026-02-26T16:00:00Z",
  },
]
